### ISSUE TITLE
8 blaze powder + 1 orange plastic in a pressure chamber = 1 blaze rod

### ISSUE THREAD

**Issue by TheDeviantCrafter** [PandaBoy444/ProjectGear#221]
You could turn common mob drops, plastic and pumpkins into obsidian.
Craft a fel pumpkin, place it on two iron bars. It becomes a blaze that drops blaze powder.
Turn it into blaze rods, make it into a blaze lamp. A pure daisy can turn that into obsidian.

**Comment by PandaBoy444** [comment]
I think we should instead use plastic sheet, because for orange plastic you need to get into pnuematicraft and plastic sheet you can get in other ways too
