### ISSUE TITLE
Add more uses for regular leather

### ISSUE THREAD

**Issue by TheDeviantCrafter** [PandaBoy444/ProjectGear#267]
Recipes:

1. Forestry backpacks: You can use leather instead of string, which gives 2 backpacks

2. RSWires bundled cable: Using leather instead of string gives 16 instead of 12

3. Magneticraft conveyor belt: Uses leather instead of iron plates

**Comment by PandaBoy444** [comment]
I don't think the backpack leather recipe should give two backpacks, in the early game leather is much easier to get than string so it doesn't make a lot of sense, but we can add a recipe using oiled leather and that can give two backpacks

**Comment by PandaBoy444** [comment]
You can also make string out of leather in a few processes so maybe we should just stay with the normal recipe

**Comment by TheDeviantCrafter** [comment]
That works.
