### ISSUE TITLE
Add some interesting ways to get XP 

### ISSUE THREAD

**Issue by PandaBoy444** [PandaBoy444/ProjectGear#297]
Add some interesting ways to get XP that are not mob farms.
liquid DNA
liquid mana
Irradiating flesh
Monster dust (maybe all of them will craft the dust and the dust will craft the xp?)

**Comment by TheDeviantCrafter** [comment]
Full mana tablet + bucket of molten lapis in an alfheim portal = bucket of primal mana

Irradiated flesh + sulfur in crafting grid = monster dust

Raw DNA/Primal Mana + monster dust in fluid agitator = liquid XP

Energite (200mb) + molten emerald = liquid XP

Those are all pretty expensive, but I think they should create a lot of liquid XP. I think auto-enchanting should be decently end game.

Another option would be a system that turns large amounts of enchanted books into small amounts of liquid XP. That would let you recycle books you don't want.

Also, we need to figure out how much liquid XP is actually required for enchanting. The numbers will depend on that information.

**Comment by PandaBoy444** [comment]
Do we have molten lapis?
I'd prefer using sulfuric acid on irradiated flesh.
I think it should be - casting energite onto crushed emerald = monster dust.
I don't think we can get enchanted books automatically, but yea, we should make such a thing possible.

**Comment by TheDeviantCrafter** [comment]
Nuclearcraft adds lapis

I'm fine with sulfuric acid

That works fine with me as well

**Comment by TheDeviantCrafter** [comment]
Random Things adds a lotus plant that can be eaten for XP.

**Comment by PandaBoy444** [comment]
Also, i'm adding monster essence which is the fluid version of monster dust

**Comment by PandaBoy444** [comment]
what do you say about Plasma/Molten Enderium/Raw DNA/Primal Mana + monster dust = liquid XP

**Comment by TheDeviantCrafter** [comment]
That would work. They all seem comparably rare.
