### ISSUE TITLE
Nerf Ore Excavator [needs discussion]

### ISSUE THREAD

**Issue by TheDeviantCrafter** [PandaBoy444/ProjectGear#310]
Here's what I'd like to do. This is of course open to feedback:

1. Increase the hunger requirement

2. If possible, make it use extra durability on Tinkers tools. This isn't hard to bypass if you made tools specifically for excavating.

3. Blacklist "filler" blocks like stone, granite, dirt, sand, marble and netherrack. That would require tools like hammers and terra shatterers which already have a pretty nice progression tree.

**Comment by TheDeviantCrafter** [comment]
Can I get some feedback on this one?

**Comment by PandaBoy444** [comment]
I like the hinger bit, durability maybe. But not thw blacklist

**Comment by Aerolfos** [comment]
Same.

**Comment by TheDeviantCrafter** [comment]
Since increasing the hunger/durability requirement wouldn't significantly impact gameplay, I'll leave the mod at the default values. Changes should be significant enough to be obvious.
