### ISSUE TITLE
Overhaul Iron Jetpacks

### ISSUE THREAD

**Issue by TheDeviantCrafter** [PandaBoy444/ProjectGear#325]
Tiers are boring. Instead, I'd like five versions to exist, each with different advantages and tradeoffs:

-Survivalist's jetpack: Cheap, energy efficient, slow
-Architech's jetpack: Perfect hover mode, poor stats everywhere else
-Adventurer's jetpack: Fast, especially for movement, but has no hover mode
-Cloudrider's jetpack: Fast, especially for vertical movement, but has no hover mode
-Base jetpack: Average stats, but excels at nothing

The stat differences should be noted in a tooltip.

**Comment by TheDeviantCrafter** [comment]
In general, all of the jetpacks except the adventurer's jetpack and cloudrider's jetpack should have fairly small batteries. Maybe 10 minutes of sustained flight. This would make them somewhat impractical if you're not in range of a wireless charger.

**Comment by PandaBoy444** [comment]
You can always make a system to swap out the empty jetpack for a full one with a player interface

**Comment by TheDeviantCrafter** [comment]
Can the system automatically detect when your jetpack is out of fuel?

You can wear an elytra bauble so you don't go on an unscheduled high velocity landing.
