### ISSUE TITLE
Add Biome Bundle as the terrain generation mod

### ISSUE THREAD

**Issue by DolphinBlaster** [PandaBoy444/ProjectGear#432]
[Biome Bundle](https://minecraft.curseforge.com/projects/biome-bundle) is my favorite terrain generation mod and I would love to see it included in this modpack. It has the best terrain generation I've ever seen and is also configurable. Also, not enough people use Biome Bundle in their modpacks so it would be nice if we did.

EDIT: I'd also like to mention that Biome Bundle also adds bigger caves which could go well with. rare ore veins.

**Comment by TheDeviantCrafter** [comment]
Biome Bundle has too many problems to include. The world creation screen is a mess, it's slow, and it seems to mess with modded worldgen that generates on a per-biome basis. I also found bedrock holes in earlier versions of the mod, but those may have been fixed.
